FAB_SIM_IP = altera_mf
NUM_TIMING_PATHS = 5
PY_TB_VHDL = [ "lab3_unsynth_pkg.vhd", "lab3_tb.vhd" ]
PIN_FILE = /home/ece327/lib/pins-NULL.tcl
PY_DESIGN_VHDL = [ "mem.vhd", "lab3.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2C35F672C
BOARD = DE2
TCL_TB_VHDL = { lab3_unsynth_pkg.vhd lab3_tb.vhd }
PHYS_SYNTH_EXT = vhd
DESIGN_ENTITY = lab3
FAMILY_SHORT = CycloneII
SH_DESIGN_VHDL = mem.vhd lab3.vhd
DESIGN_ARCH = main
FREQ_MIN = 50
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = /home/ece327
LIB_VHDL = 
SH_TB_VHDL = lab3_unsynth_pkg.vhd lab3_tb.vhd
TB_ENTITY = lab3_tb
GOAL_FREQ = 250
USE_GUI = False
TB_VHDL = lab3_unsynth_pkg.vhd, lab3_tb.vhd
SIM_SCRIPT = lab3_tb.sim
RPT_DIR = RPT
FAB_SIM_HOME = /home/ece327/altera
LOGIC_SYNTH_EXT = edf
RPT_TDIR = RPT
FAMILY_LONG = Cyclone II
TCL_DESIGN_VHDL = { mem.vhd lab3.vhd }
INTERACTIVE_FLAG = False
SPEED = 7
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = lab3
TB_ARCH = main
SH_LIB_VHDL = 
LC_FAMILY_SHORT = cycloneii
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
TCL_LIB_VHDL = {  }
DESIGN_VHDL = mem.vhd, lab3.vhd
GUI_FLAG = -shell
PY_LIB_VHDL = []
